server:
  servlet:
    context-path: /api

openweather:
  url: http://api.openweathermap.org
  api-key: ${API_KEY}

weather:
  cache:
    expiration-minutes: 5}
    size: ${CACHE_SIZE}
  scheduled: ${WEATHER_SCHEDULED:false}
  scheduler:
    fixedRate: ${EXPIRATION_MINUTES:600000}
